set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g window-status-style "bg=default,fg=white"
set -g status-style "bg=default"
set -g window-status-current-style "bg=#262a33,fg=#e5e5e5"
# set -g window-status-current-style "bg=#2e3440,fg=#d8dee9"
# set -g window-status-current-style "bg=#3c4451,fg=#c0c0c0"
# set -g window-status-current-style "bg=#ffb86c,fg=#1e1e1e"
# set -g window-status-current-style "bg=#44475a,fg=#f8f8f2"
# set -g window-status-current-style "bg=#3a3f5a,fg=#ffffff"
# set -g window-status-current-style "bg=#005f5f,fg=#ffffff"
# set -g window-status-current-style "bg=#6272a4,fg=#f8f8f2"
# set -g window-status-current-style "bg=#ffb86c,fg=#1e1e1e"
# set -g window-status-current-style "bg=#ff5555,fg=#1e1e1e"
# set -g window-status-current-style "bg=#50fa7b,fg=#1e1e1e"

set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

set -g status-justify left
set -g status-bg default
set -g status-fg white
set -g status-left "  "
set -g status-right ""

unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

bind -T root C-h copy-mode
bind -T copy-mode C-j send-keys -X page-down
bind -T copy-mode C-k send-keys -X page-up
bind -T copy-mode C-q send-keys -X cancel

# setw -g mouse on

setw -g mouse off          # terminal scroll stays terminal’s job
set -g mode-keys vi        # vim-like copy mode
set -g history-limit 100000

# enter copy-mode with C-h (you already have that)
bind -T root C-h copy-mode

# copy-mode (vi) navigation and search
bind -T copy-mode-vi h send -X cursor-left
bind -T copy-mode-vi j send -X cursor-down
bind -T copy-mode-vi k send -X cursor-up
bind -T copy-mode-vi l send -X cursor-right

unbind -T copy-mode-vi s
bind -T copy-mode-vi s command-prompt -p "search:" "send -X search-forward '%%'"

bind -T copy-mode-vi ? send -X search-backward
bind -T copy-mode-vi n send -X search-again
bind -T copy-mode-vi N send -X search-reverse

# copy/paste
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind p paste-buffer

# leave copy-mode
bind -T copy-mode-vi q send -X cancel

# styling for repeat indicator at the bottom
set -g message-command-style 'fg=default,bg=default'
set -g message-style 'fg=default,bg=default'

###############

bind Q confirm-before -p "kill-session #S? (y/n)" kill-session
bind-key b set-option status

run '~/.tmux/plugins/tpm/tpm'
