set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @minimal-tmux-indicator false
set -g @minimal-tmux-left false
set -g @minimal-tmux-right false
set -g @minimal-tmux-bg "default"
set -g @minimal-tmux-fg "#ffffff"
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-status-left-extra " "

unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

bind -T root C-h copy-mode
bind -T copy-mode C-j send-keys -X page-down
bind -T copy-mode C-k send-keys -X page-up
bind -T copy-mode C-q send-keys -X cancel

setw -g mouse on

bind Q confirm-before -p "kill-session #S? (y/n)" kill-session
bind-key b set-option status

run '~/.tmux/plugins/tpm/tpm'



















